/**
 * 自动出题：四种题型生成、确定性 ID、选项构造。
 */
import type { Clause, ContentData, Formula, SymptomTerm } from '../../data/types'
import { createAutoQuestionId, fnv1a } from './hash'
import type { AutoGeneratedQuestion } from './types'

const BLANK = '＿＿＿'

interface OptionSet {
  options: string[]
  answerIndex: number
}

/**
 * 生成 4 个不重复选项，并用 seed 做确定性轮转。
 */
function buildOptions(correct: string, distractors: string[], seed: string): OptionSet | null {
  const candidates = Array.from(new Set([correct, ...distractors])).slice(0, 4)
  if (candidates.length < 4 || !candidates.includes(correct)) {
    return null
  }
  const offset = fnv1a(seed) % candidates.length
  const rotated = [...candidates.slice(offset), ...candidates.slice(0, offset)]
  const answerIndex = rotated.indexOf(correct)
  return { options: rotated, answerIndex }
}

function termName(id: string, terms: SymptomTerm[]): string | undefined {
  return terms.find((term) => term.id === id)?.name
}

function herbName(id: string, content: ContentData): string | undefined {
  return content.herbs.find((herb) => herb.id === id)?.name
}

/**
 * 挖空选择题：从原文挖掉一个症状/脉象/病机关键词。
 */
export function generateFillBlank(
  clause: Clause,
  content: ContentData
): AutoGeneratedQuestion | null {
  const termsInText = content.symptomTerms.filter(
    (term) => clause.symptomTags.includes(term.id) && clause.text.includes(term.name)
  )
  const correctTerm =
    termsInText.find((term) => term.name.length >= 2) ??
    termsInText[0] ??
    content.symptomTerms.find((term) => clause.text.includes(term.name))

  if (!correctTerm || !clause.text.includes(correctTerm.name)) {
    return null
  }

  const sameCategory = content.symptomTerms.filter(
    (term) => term.id !== correctTerm.id && term.category === correctTerm.category
  )
  const distractors = [
    ...sameCategory.map((term) => term.name),
    ...content.symptomTerms.filter((term) => term.id !== correctTerm.id).map((term) => term.name),
  ]
  const optionSet = buildOptions(
    correctTerm.name,
    distractors,
    `${clause.id}.fill_blank.${correctTerm.name}`
  )
  if (!optionSet) {
    return null
  }

  const prompt = clause.text.replace(correctTerm.name, BLANK)
  return {
    id: createAutoQuestionId(
      content.book.code,
      content.edition.code,
      clause.id,
      'fill_blank',
      correctTerm.name
    ),
    type: 'fill_blank',
    clause: clause.id,
    prompt,
    options: optionSet.options,
    answerIndex: optionSet.answerIndex,
    rationale: `原文“${clause.text}”`,
    status: 'auto',
  }
}

interface ClauseSplit {
  head: string
  tail: string
}

function splitClauseText(text: string): ClauseSplit | null {
  const chars = Array.from(text)
  const minIndex = Math.floor(chars.length / 3)
  for (let i = minIndex; i < chars.length - 1; i += 1) {
    if ('，。；！？、'.includes(chars[i])) {
      return { head: chars.slice(0, i + 1).join(''), tail: chars.slice(i + 1).join('') }
    }
  }
  const half = Math.floor(chars.length / 2)
  if (half === 0 || half === chars.length) {
    return null
  }
  return { head: chars.slice(0, half).join(''), tail: chars.slice(half).join('') }
}

/**
 * 条文接龙：给出上半句，四选一补全下半句。
 */
export function generateClauseChain(
  clause: Clause,
  content: ContentData
): AutoGeneratedQuestion | null {
  const split = splitClauseText(clause.text)
  if (!split || !split.tail.trim()) {
    return null
  }

  const distractors = content.clauses
    .filter((item) => item.id !== clause.id)
    .map((item) => splitClauseText(item.text)?.tail)
    .filter((tail): tail is string => Boolean(tail && tail.trim()))

  const optionSet = buildOptions(split.tail, distractors, `${clause.id}.clause_chain.${split.tail}`)
  if (!optionSet) {
    return null
  }

  return {
    id: createAutoQuestionId(
      content.book.code,
      content.edition.code,
      clause.id,
      'clause_chain',
      split.tail
    ),
    type: 'clause_chain',
    clause: clause.id,
    prompt: `${split.head}${BLANK}`,
    options: optionSet.options,
    answerIndex: optionSet.answerIndex,
    rationale: `原文“${clause.text}”`,
    status: 'auto',
  }
}

/**
 * 方证匹配：给症状标签，选对应方剂。
 */
export function generateFormulaSyndromeMatch(
  clause: Clause,
  content: ContentData
): AutoGeneratedQuestion | null {
  const formula =
    content.formulas.find((item) => clause.formulas.includes(item.id)) ??
    content.formulas.find((item) => item.relatedClauses.includes(clause.id))

  if (!formula) {
    return null
  }

  const symptomNames = clause.symptomTags
    .map((id) => termName(id, content.symptomTerms))
    .filter((name): name is string => Boolean(name))

  const distractors = content.formulas
    .filter((item) => item.id !== formula.id)
    .map((item) => item.name)

  const optionSet = buildOptions(
    formula.name,
    distractors,
    `${formula.id}.formula_syndrome_match.${clause.id}`
  )
  if (!optionSet) {
    return null
  }

  return {
    id: createAutoQuestionId(
      content.book.code,
      content.edition.code,
      formula.id,
      'formula_syndrome_match',
      clause.id
    ),
    type: 'formula_syndrome_match',
    clause: clause.id,
    formula: formula.id,
    prompt: `条文症状：${symptomNames.join('、')}。以下哪首方最可能对应？`,
    options: optionSet.options,
    answerIndex: optionSet.answerIndex,
    rationale: `条文“${clause.text}”对应《${formula.name}》。`,
    status: 'auto',
  }
}

/**
 * 方剂组成：判断某味药是否不属于某方。
 */
export function generateFormulaComposition(
  formula: Formula,
  content: ContentData
): AutoGeneratedQuestion | null {
  const compositionIds = formula.composition.map((item) => item.herb)
  const inHerbNames = compositionIds
    .map((id) => herbName(id, content))
    .filter((name): name is string => Boolean(name))
  const outsideHerbNames = content.herbs
    .filter((herb) => !compositionIds.includes(herb.id))
    .map((herb) => herb.name)

  if (inHerbNames.length < 3 || outsideHerbNames.length === 0) {
    return null
  }

  const correct = outsideHerbNames[0]
  const optionSet = buildOptions(
    correct,
    inHerbNames,
    `${formula.id}.formula_composition.${correct}`
  )
  if (!optionSet) {
    return null
  }

  return {
    id: createAutoQuestionId(
      content.book.code,
      content.edition.code,
      formula.id,
      'formula_composition',
      correct
    ),
    type: 'formula_composition',
    clause: formula.relatedClauses[0] ?? '',
    formula: formula.id,
    prompt: `以下哪味药不属于「${formula.name}」？`,
    options: optionSet.options,
    answerIndex: optionSet.answerIndex,
    rationale: `「${formula.name}」由 ${inHerbNames.join('、')} 组成，不含${correct}。`,
    status: 'auto',
  }
}

/**
 * 生成全部可生成的自动题。
 * @param content 内容数据
 * @param clauseId 可选，只生成指定条文的题
 * @returns 自动题列表
 */
export function generateAutoQuestions(
  content: ContentData,
  clauseId?: string
): AutoGeneratedQuestion[] {
  const clauses = clauseId
    ? content.clauses.filter((item) => item.id === clauseId)
    : content.clauses
  const questions: Array<AutoGeneratedQuestion | null> = []

  for (const clause of clauses) {
    questions.push(generateFillBlank(clause, content))
    questions.push(generateClauseChain(clause, content))
    questions.push(generateFormulaSyndromeMatch(clause, content))
  }

  for (const formula of content.formulas) {
    questions.push(generateFormulaComposition(formula, content))
  }

  return questions.filter((question): question is AutoGeneratedQuestion => question !== null)
}
