/**
 * 出题模块类型。
 */
import type { QuestionType } from '../../data/types'

export interface AutoGeneratedQuestion {
  id: string
  type: QuestionType
  clause: string
  formula?: string
  prompt: string
  options: string[]
  answerIndex: number
  rationale: string
  status: 'auto'
}
